/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "STD_Types.h"
#include "BIT_Math.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"



#include "LCD_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_voidInit();


	LCD_voidInit(LCD_enum_4BITS_MODE);
	LCD_voidGoTo(0, 5);
	LCD_voidWriteString((u8*)"Welcome");
	LCD_voidGoTo(1, 3);
	LCD_voidWriteString((u8*)"4 BITS Mode");


    /* Loop forever */
	while(1)
	{

	}
}

