/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "STD_Types.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"

#include "keypad_Config.h"
#include "keypad_Interface.h"
#include "LCD_interface.h"
#include "SEVSEG_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_voidInit();

	RCC_voidEnablePeripheralCLK(RCC_AHB1, RCC_GPIOA_EN);
	RCC_voidEnablePeripheralCLK(RCC_AHB1, RCC_GPIOB_EN);
	LCD_voidInit(LCD_enum_4BITS_MODE);



	KeyPad_void_intialize();



	u8 KeyNum;
	LCD_voidGoTo(0, 3);
	LCD_voidWriteString((u8*)"KeyPad :");


	while(1)
	{
		KeyNum = KEYPAD_u8GetPressedKey();
			if((KeyNum >= 0) && (KeyNum <= 9))
			{
				LCD_voidGoTo(1, 5);
				LCD_voidPrintUnsignedInteger(KeyNum);
			}
	}
}
