/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STD_Types.h"
#include "BIT_Math.h"

#include "RCC_interface.h"

#include "GPIO_interface.h"
#include "GPIO_private.h"
#include "SEVSEG_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void _delay_ms(u32 Copy_u32Time)
{
	for(u32 i = 0 ; i < Copy_u32Time ; i++)
	{
		for(u16 j = 0 ; j < 565 ; j++)
		{
			asm("NOP");
		}
	}
}

int main(void)
{

    RCC_voidInit();
    RCC_voidEnablePeripheralCLK(RCC_AHB1, RCC_GPIOA_EN);
    SEVSEG_voidInitilize();

//    GPIO_voidSetPinDirection(GPIOA, GPIO_PIN9,  GPIO_OUTPUT, GPIO_OUTPUT_PUSHPULL);
//    GPIO_voidSetPinValue(SEG_1_PORT, SEG0_b_PIN,HIGH);
//    SEVSEG_voidDisplay(SEG1, 4);


    /* Loop forever */

	while(1)
	{
		SEVSEG_voidCount();
	}
}
